### ISSUE TITLE
Mobile loading freezing in SCORM

### ISSUE THREAD

**Issue by papakoala** [Mimiste/c2-scorm-plugin#2]
Hi Loïc!
Thanks for your pluggin, I was excited when I saw it but I cannot get it working on mobile.  I'm experiencing a problem when I load the exported HTML5 game to Scorm Cloud, it works via laptop, communication with the LMS works which is great. But when I try to access via mobile (iphone, iPad etc) construct2 loader freezes (doesn't even start).
You can reproduce this behaviour with the "Scorm tutorial folder" that you provide and it happens with my game as well. 
However, when it doesn't go through the Scorm player - that is, when I upload it to a regular website without SCORM it loads perfectly from mobile.
The question is, may be something related to the pluggin that freezes the loading when accessing to the resource from mobile? 
Do you have any ideas why thig might be going on?

**Comment by papakoala** [comment]
I should close this issue as it's not related to your plugin at all.... Its the "CrossOrigin" property that was being set on the loading objects as "anonymous".

**Comment by loic-martinez-freelance** [comment]
Exact, that's a problem you can face on a lot of LMS with Construct 2 modules. I should try to understand why it's causing problems and maybe send the results to Scirra..
